In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
# Vocablury size 
vocab_size = 10000

In [5]:
# One hot representation
onehot_rep = [one_hot(words,vocab_size) for words in sent] #In one_hot we pass the string of sentence and the vocabulary size 
print(onehot_rep)

[[8142, 2185, 274, 1874], [8142, 2185, 274, 5043], [8142, 6498, 274, 7625], [9621, 6954, 3840, 2891, 4187], [9621, 6954, 3840, 2891, 4472], [8203, 8142, 6622, 274, 251], [9334, 4199, 4568, 2891]]


In [9]:
# Word Embedding represetation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

# Pad_sequence is to ensure that the lenght of words in each sentence is same
sent_len = 8
embedded_doc = pad_sequences(onehot_rep, padding = 'pre', maxlen = sent_len) #Pre will add zeros in the preceeding
print(embedded_doc)

[[   0    0    0    0 8142 2185  274 1874]
 [   0    0    0    0 8142 2185  274 5043]
 [   0    0    0    0 8142 6498  274 7625]
 [   0    0    0 9621 6954 3840 2891 4187]
 [   0    0    0 9621 6954 3840 2891 4472]
 [   0    0    0 8203 8142 6622  274  251]
 [   0    0    0    0 9334 4199 4568 2891]]


In [21]:
# Assigning number of features wanted
dim = 10

Embedding layer

In [22]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_len))
model.compile('adam', 'mse')

In [23]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(embedded_doc))

1/1 [==============================] - 0s 86ms/step
[[[-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204
    0.00052805 -0.00909277  0.04849864 -0.03014334  0.01647795]
  [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204
    0.00052805 -0.00909277  0.04849864 -0.03014334  0.01647795]
  [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204
    0.00052805 -0.00909277  0.04849864 -0.03014334  0.01647795]
  [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204
    0.00052805 -0.00909277  0.04849864 -0.03014334  0.01647795]
  [-0.03304784 -0.03011279 -0.03166356  0.00138807  0.03015063
   -0.03435756 -0.01307648 -0.0454451  -0.01140922  0.03483594]
  [ 0.00731983 -0.0019669   0.00572064 -0.00089065 -0.00156641
    0.00839043  0.00090306  0.04628556  0.01745952  0.00102956]
  [ 0.04226412  0.01217443 -0.04219994  0.01620353 -0.02582815
   -0.04285703  0.00147092 -0.04539495 -0.02734694  0.02620686]
  [-0.0288959   0.03095842 -0.00386565  0.01981794  0.01878

In [25]:
print(embedded_doc[0]) # Shape is 8,

[   0    0    0    0 8142 2185  274 1874]


In [26]:
print(model.predict(embedded_doc[0])) # Will get each word represented by 10 features or total shape will be 8 x 10

1/1 [==============================] - 0s 81ms/step
[[-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204  0.00052805
  -0.00909277  0.04849864 -0.03014334  0.01647795]
 [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204  0.00052805
  -0.00909277  0.04849864 -0.03014334  0.01647795]
 [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204  0.00052805
  -0.00909277  0.04849864 -0.03014334  0.01647795]
 [-0.04302913 -0.04835535  0.02072377  0.00895243  0.01936204  0.00052805
  -0.00909277  0.04849864 -0.03014334  0.01647795]
 [-0.03304784 -0.03011279 -0.03166356  0.00138807  0.03015063 -0.03435756
  -0.01307648 -0.0454451  -0.01140922  0.03483594]
 [ 0.00731983 -0.0019669   0.00572064 -0.00089065 -0.00156641  0.00839043
   0.00090306  0.04628556  0.01745952  0.00102956]
 [ 0.04226412  0.01217443 -0.04219994  0.01620353 -0.02582815 -0.04285703
   0.00147092 -0.04539495 -0.02734694  0.02620686]
 [-0.0288959   0.03095842 -0.00386565  0.01981794  0.01878643 -0.01867244