In [1]:
# Input (temp, rainfall, humidity)
import numpy as np
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [2]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [14]:
import torch
inputs= torch.tensor(inputs)
targets = torch.tensor(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


C:\Users\RuturajMane\AppData\Local\Temp\ipykernel_10496\856546539.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs= torch.tensor(inputs)
C:\Users\RuturajMane\AppData\Local\Temp\ipykernel_10496\856546539.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets)


In [26]:
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2,requires_grad = True)

In [27]:
def model(x):
    return (x @ (w.t()))+b

In [45]:
pred = model(inputs)
print(pred)
print(targets)

tensor([[  9.1601,  50.3071],
        [ 15.6685,  65.6587],
        [  3.9821, 119.0103],
        [ 10.5930,  18.9578],
        [ 17.2361,  77.7575]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [46]:
# loss function
def mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [47]:
loss = mse(pred, targets)
print(loss)

tensor(3103.5847, grad_fn=<DivBackward0>)


In [48]:
loss.backward()
print(w)
print(w.grad)

tensor([[-0.0032, -0.1889,  0.5015],
        [-0.2020,  1.1148, -0.2106]], requires_grad=True)
tensor([[-5290.4512, -6604.7349, -3858.3799],
        [-2111.3547, -2207.8328, -1494.9143]])


In [49]:
with torch.no_grad():
    w-= (w.grad*1e-5)
    b-= (b.grad*1e-5)
    w.grad.zero_()
    b.grad.zero_()
print(w)
print(b)

tensor([[ 0.0497, -0.1229,  0.5401],
        [-0.1809,  1.1369, -0.1957]], requires_grad=True)
tensor([ 0.4821, -0.5806], requires_grad=True)


In [50]:
pred = model(inputs)
loss = mse(pred, targets)
print(loss)

tensor(2210.3462, grad_fn=<DivBackward0>)


In [55]:
for i in range(100):
    pred = model(inputs)
    loss = mse(pred, targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [57]:
print(w)
print(loss)
print(pred)

tensor([[-0.2231,  0.6380,  0.7520],
        [-0.1004,  1.1448,  0.0486]], requires_grad=True)
tensor(66.6971, grad_fn=<DivBackward0>)
tensor([[ 59.2930,  70.8806],
        [ 84.4657,  94.1268],
        [110.1366, 146.9194],
        [ 33.0642,  40.2015],
        [ 98.9521, 105.7811]], grad_fn=<AddBackward0>)
