In [1]:
# Input (temp, rainfall, humidity)
import numpy as np
import torch
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [2]:
from torch.utils.data import TensorDataset

In [11]:
train_ds = TensorDataset(inputs, targets)
print(len(train_ds))
train_ds[0:3]


15


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle= False)

In [9]:
i = 1
for xb,yb in train_dl:
    print('Batch  :', i)
    print(xb)
    print(yb)
    i+=1

Batch  : 1
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
Batch  : 2
tensor([[ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.]])
tensor([[ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.]])
Batch  : 3
tensor([[ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [20]:
import torch.nn
model = torch.nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3843,  0.1400, -0.3462],
        [-0.1574,  0.1146,  0.1994]], requires_grad=True)
Parameter containing:
tensor([ 0.5290, -0.4005], requires_grad=True)


In [25]:
pred = model(inputs)
print(pred)

tensor([[23.0777,  4.3643],
        [25.6650,  8.1255],
        [32.6475, 12.8308],
        [32.9387, -4.1458],
        [16.2533, 13.7003],
        [23.3220,  4.0924],
        [25.1787,  8.2102],
        [32.6856, 12.8728],
        [32.6945, -3.8738],
        [15.5228, 14.0570],
        [22.5914,  4.4491],
        [25.9093,  7.8535],
        [33.1338, 12.7461],
        [33.6693, -4.5025],
        [16.0091, 13.9723]], grad_fn=<AddmmBackward0>)


In [26]:
# loss function
import torch.nn.functional as F

In [28]:
loss_fun = F.mse_loss

In [29]:
loss = loss_fun(model(inputs), targets)
print(loss)

tensor(5935.5454, grad_fn=<MseLossBackward0>)


In [37]:
# Optimizer
import torch.optim
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [46]:
def fit(num_epochs, model, loss_fun, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb, yb in train_dl:
            
            pred = model(xb)
            
            loss = loss_fun(pred, yb)
            
            loss.backward()
            
            opt.step()
            
            opt.zero_grad()
            
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [47]:
fit(100,model,loss_fun,opt, train_dl)

Epoch [10/100], Loss: 483.6180
Epoch [20/100], Loss: 198.6450
Epoch [30/100], Loss: 249.1896
Epoch [40/100], Loss: 170.8644
Epoch [50/100], Loss: 109.6234
Epoch [60/100], Loss: 98.3452
Epoch [70/100], Loss: 55.0681
Epoch [80/100], Loss: 60.2695
Epoch [90/100], Loss: 59.5787
Epoch [100/100], Loss: 24.0933
