In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from keras.preprocessing.sequence import TimeseriesGenerator
from IPython.display import Image,display

mpl.rcParams['figure.figsize'] = (14,7)
mpl.rcParams['axes.grid'] = False

In [3]:
df = pd.read_csv('energydata_complete.csv')

In [4]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [6]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
df = df.set_index(df['date'] )

In [8]:
df.head()

date  Appliances  lights     T1       RH_1  \
date                                                                            
2016-01-11 17:00:00 2016-01-11 17:00:00          60      30  19.89  47.596667   
2016-01-11 17:10:00 2016-01-11 17:10:00          60      30  19.89  46.693333   
2016-01-11 17:20:00 2016-01-11 17:20:00          50      30  19.89  46.300000   
2016-01-11 17:30:00 2016-01-11 17:30:00          50      40  19.89  46.066667   
2016-01-11 17:40:00 2016-01-11 17:40:00          60      40  19.89  46.333333   

                       T2       RH_2     T3       RH_3         T4  ...  \
date                                                               ...   
2016-01-11 17:00:00  19.2  44.790000  19.79  44.730000  19.000000  ...   
2016-01-11 17:10:00  19.2  44.722500  19.79  44.790000  19.000000  ...   
2016-01-11 17:20:00  19.2  44.626667  19.79  44.933333  18.926667  ...   
2016-01-11 17:30:00  19.2  44.590000  19.79  45.000000  18.890000  ...   
2016-01-11 17:40:00  19.2  44.530000  19.79  45.000000  18.890000  ...   

                            T9   RH_9     T_out  Press_mm_hg  RH_out  \
date                                                                   
2016-01-11 17:00:00  17.033333  45.53  6.600000        733.5    92.0   
2016-01-11 17:10:00  17.066667  45.56  6.483333        733.6    92.0   
2016-01-11 17:20:00  17.000000  45.50  6.366667        733.7    92.0   
2016-01-11 17:30:00  17.000000  45.40  6.250000        733.8    92.0   
2016-01-11 17:40:00  17.000000  45.40  6.133333        733.9    92.0   

                     Windspeed  Visibility  Tdewpoint        rv1        rv2  
date                                                                         
2016-01-11 17:00:00   7.000000   63.000000        5.3  13.275433  13.275433  
2016-01-11 17:10:00   6.666667   59.166667        5.2  18.606195  18.606195  
2016-01-11 17:20:00   6.333333   55.333333        5.1  28.642668  28.642668  
2016-01-11 17:30:00   6.000000   51.500000        5.0  45.410389  45.410389  
2016-01-11 17:40:00   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [9]:
df.drop(['date'], axis =1, inplace = True)

In [10]:
df.head()

Appliances  lights     T1       RH_1    T2       RH_2  \
date                                                                         
2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

                        T3       RH_3         T4       RH_4  ...         T9  \
date                                                         ...              
2016-01-11 17:00:00  19.79  44.730000  19.000000  45.566667  ...  17.033333   
2016-01-11 17:10:00  19.79  44.790000  19.000000  45.992500  ...  17.066667   
2016-01-11 17:20:00  19.79  44.933333  18.926667  45.890000  ...  17.000000   
2016-01-11 17:30:00  19.79  45.000000  18.890000  45.723333  ...  17.000000   
2016-01-11 17:40:00  19.79  45.000000  18.890000  45.530000  ...  17.000000   

                      RH_9     T_out  Press_mm_hg  RH_out  Windspeed  \
date                                                                   
2016-01-11 17:00:00  45.53  6.600000        733.5    92.0   7.000000   
2016-01-11 17:10:00  45.56  6.483333        733.6    92.0   6.666667   
2016-01-11 17:20:00  45.50  6.366667        733.7    92.0   6.333333   
2016-01-11 17:30:00  45.40  6.250000        733.8    92.0   6.000000   
2016-01-11 17:40:00  45.40  6.133333        733.9    92.0   5.666667   

                     Visibility  Tdewpoint        rv1        rv2  
date                                                              
2016-01-11 17:00:00   63.000000        5.3  13.275433  13.275433  
2016-01-11 17:10:00   59.166667        5.2  18.606195  18.606195  
2016-01-11 17:20:00   55.333333        5.1  28.642668  28.642668  
2016-01-11 17:30:00   51.500000        5.0  45.410389  45.410389  
2016-01-11 17:40:00   47.666667        4.9  10.084097  10.084097  

[5 rows x 28 columns]

In [11]:
df.count()

Appliances     19735
lights         19735
T1             19735
RH_1           19735
T2             19735
RH_2           19735
T3             19735
RH_3           19735
T4             19735
RH_4           19735
T5             19735
RH_5           19735
T6             19735
RH_6           19735
T7             19735
RH_7           19735
T8             19735
RH_8           19735
T9             19735
RH_9           19735
T_out          19735
Press_mm_hg    19735
RH_out         19735
Windspeed      19735
Visibility     19735
Tdewpoint      19735
rv1            19735
rv2            19735
dtype: int64

In [12]:
features = df[['Appliances', 'T_out','RH_2']].to_numpy().tolist()
target = df['Appliances'].tolist()

In [13]:
features[:11]

[[60.0, 6.6, 44.79],
 [60.0, 6.48333333333333, 44.7225],
 [50.0, 6.36666666666667, 44.6266666666667],
 [50.0, 6.25, 44.59],
 [60.0, 6.133333333333329, 44.53],
 [50.0, 6.01666666666667, 44.5],
 [60.0, 5.9, 44.5],
 [60.0, 5.91666666666667, 44.5],
 [60.0, 5.93333333333333, 44.433333333333294],
 [70.0, 5.95, 44.4],
 [230.0, 5.96666666666667, 44.4]]

In [14]:
target[:11]

[60, 60, 50, 50, 60, 50, 60, 60, 60, 70, 230]

In [15]:
ts_generator = TimeseriesGenerator(features, target, length =6, sampling_rate=1, batch_size=1)

In [16]:
ts_generator[0]

(array([[[60.        ,  6.6       , 44.79      ],
         [60.        ,  6.48333333, 44.7225    ],
         [50.        ,  6.36666667, 44.62666667],
         [50.        ,  6.25      , 44.59      ],
         [60.        ,  6.13333333, 44.53      ],
         [50.        ,  6.01666667, 44.5       ]]]),
 array([60]))

In [18]:
ts_generator[0][0].shape

(1, 6, 3)

- Shape of input is like (batch size, timestamp/steps, features)

- Input 1,2,3,4,5,6,7,8,9

sliding window (window size - 3, stride - 1) - input - 1,2,3 target - (4) 2,3,4 (5)
sliding window (window size - 3, stride - 2) - input - 1,2,3 target - (4) 3,4,5 (6)
tumbling/ Hopping window (Window size -3) - 1,2,3 (4) 4,5,6 (7)

In [19]:
len(ts_generator)

19729

In [20]:
ts_generator = TimeseriesGenerator(features, target, length =6, sampling_rate=1, batch_size=1, stride =2)

In [21]:
len(ts_generator)

9865

- length gets half as we are hopping by two places

In [23]:
pd.concat([df['Appliances'], df['Appliances'].shift(-1), df['Appliances'].shift(-2)], axis =1)

Appliances  Appliances  Appliances
date                                                   
2016-01-11 17:00:00          60        60.0        50.0
2016-01-11 17:10:00          60        50.0        50.0
2016-01-11 17:20:00          50        50.0        60.0
2016-01-11 17:30:00          50        60.0        50.0
2016-01-11 17:40:00          60        50.0        60.0
...                         ...         ...         ...
2016-05-27 17:20:00         100        90.0       270.0
2016-05-27 17:30:00          90       270.0       420.0
2016-05-27 17:40:00         270       420.0       430.0
2016-05-27 17:50:00         420       430.0         NaN
2016-05-27 18:00:00         430         NaN         NaN

[19735 rows x 3 columns]

In [27]:
multi_target = pd.concat([df['Appliances'], df['Appliances'].shift(-1), df['Appliances'].shift(-2)], axis =1).dropna().to_numpy().tolist()

In [28]:
multi_target[:13]

[[60.0, 60.0, 50.0],
 [60.0, 50.0, 50.0],
 [50.0, 50.0, 60.0],
 [50.0, 60.0, 50.0],
 [60.0, 50.0, 60.0],
 [50.0, 60.0, 60.0],
 [60.0, 60.0, 60.0],
 [60.0, 60.0, 70.0],
 [60.0, 70.0, 230.0],
 [70.0, 230.0, 580.0],
 [230.0, 580.0, 430.0],
 [580.0, 430.0, 250.0],
 [430.0, 250.0, 100.0]]

## Model Buidling

In [30]:
from sklearn.model_selection import train_test_split
from keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import tensorflow as tf

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19735 entries, 2016-01-11 17:00:00 to 2016-05-27 18:00:00
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Appliances   19735 non-null  int64  
 1   lights       19735 non-null  int64  
 2   T1           19735 non-null  float64
 3   RH_1         19735 non-null  float64
 4   T2           19735 non-null  float64
 5   RH_2         19735 non-null  float64
 6   T3           19735 non-null  float64
 7   RH_3         19735 non-null  float64
 8   T4           19735 non-null  float64
 9   RH_4         19735 non-null  float64
 10  T5           19735 non-null  float64
 11  RH_5         19735 non-null  float64
 12  T6           19735 non-null  float64
 13  RH_6         19735 non-null  float64
 14  T7           19735 non-null  float64
 15  RH_7         19735 non-null  float64
 16  T8           19735 non-null  float64
 17  RH_8         19735 non-null  float64
 18  T9         

In [32]:
df_input = df[['Appliances', 'T_out','RH_1','Visibility']]

In [33]:
df_input.head()

Appliances     T_out       RH_1  Visibility
date                                                            
2016-01-11 17:00:00          60  6.600000  47.596667   63.000000
2016-01-11 17:10:00          60  6.483333  46.693333   59.166667
2016-01-11 17:20:00          50  6.366667  46.300000   55.333333
2016-01-11 17:30:00          50  6.250000  46.066667   51.500000
2016-01-11 17:40:00          60  6.133333  46.333333   47.666667

In [34]:
df_input.describe()

Appliances         T_out          RH_1    Visibility
count  19735.000000  19735.000000  19735.000000  19735.000000
mean      97.694958      7.411665     40.259739     38.330834
std      102.524891      5.317409      3.979299     11.794719
min       10.000000     -5.000000     27.023333      1.000000
25%       50.000000      3.666667     37.333333     29.000000
50%       60.000000      6.916667     39.656667     40.000000
75%      100.000000     10.408333     43.066667     40.000000
max     1080.000000     26.100000     63.360000     66.000000

- Finding the outlier

In [35]:
df_input.query('Appliances > 500')

Appliances      T_out       RH_1  Visibility
date                                                             
2016-01-11 18:50:00         580   5.983333  46.396667   40.000000
2016-01-13 21:20:00         520   2.900000  41.530000   36.333333
2016-01-14 10:20:00         550   2.033333  43.433333   40.000000
2016-01-14 10:30:00         690   2.100000  43.766667   40.000000
2016-01-14 10:40:00         620   2.166667  43.693333   40.000000
...                         ...        ...        ...         ...
2016-05-26 17:20:00         600  20.833333  44.066667   40.000000
2016-05-26 17:30:00         520  20.900000  43.366667   40.000000
2016-05-27 09:40:00         580  15.900000  47.226667   61.000000
2016-05-27 09:50:00         660  16.100000  47.693333   61.000000
2016-05-27 11:30:00         620  19.100000  48.326667   64.000000

[288 rows x 4 columns]

### As seen above there are some outlier and StandardScaler pushes mean and variance or gets affected by oulier so it is better to use the MinMaxScaler

In [36]:
x_train = df_input.iloc[:15000]
y_train = df['Appliances'].iloc[:15000]

x_test = df_input.iloc[15000:]
y_test = df['Appliances'].iloc[15000:]

In [37]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [39]:
x_test

array([[0.07476636, 0.36842105, 0.2180015 , 0.6       ],
       [0.09345794, 0.36234818, 0.21519461, 0.6       ],
       [0.07476636, 0.3562753 , 0.21519461, 0.6       ],
       ...,
       [0.24299065, 1.1120108 , 0.52947231, 0.37435897],
       [0.38317757, 1.10661269, 0.54051272, 0.38717949],
       [0.39252336, 1.10121457, 0.52956587, 0.4       ]])

In [40]:
x_train

array([[0.04672897, 0.46963563, 0.55754117, 0.95384615],
       [0.04672897, 0.46491228, 0.53218563, 0.89487179],
       [0.03738318, 0.46018893, 0.52114521, 0.83589744],
       ...,
       [0.09345794, 0.39271255, 0.21706587, 0.6       ],
       [0.09345794, 0.38461538, 0.21519461, 0.6       ],
       [0.08411215, 0.37651822, 0.2180015 , 0.6       ]])

In [41]:
x_test.shape

(4735, 4)

In [42]:
x_train.shape

(15000, 4)

In [43]:
win_length = 720
batch_size = 32
num_features = 4
train_generator = TimeseriesGenerator(x_train, y_train, length = win_length, sampling_rate =1, batch_size = batch_size)
test_generator = TimeseriesGenerator(x_test, y_test, length = win_length, sampling_rate =1, batch_size = batch_size)

In [46]:
train_generator[0][0].shape

(32, 720, 4)

- Shape (Batch size, no. of time stamps, features)

In [47]:
train_generator[0][1]

array([  80,  150,  380,  290,  270,  420,  280,  300,  350,  270,  560,
       1080,  750,  390,  350,  340,  290,  230,  120,  110,  100,  110,
        130,  140,  110,  100,  100,  110,  110,  190,  450,  210],
      dtype=int64)

- Defining / Initializing the model

In [49]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.LSTM(128, input_shape = (win_length, num_features), return_sequences = True))
model.add(tf.keras.layers.LeakyReLU(alpha = 0.5))
model.add(tf.keras.layers.LSTM(128, return_sequences = True))
model.add(tf.keras.layers.LeakyReLU(alpha = 0.5))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.LSTM(64, return_sequences = False))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Dense(1))

In [50]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 720, 128)          68096     
                                                                 
 leaky_re_lu_2 (LeakyReLU)   (None, 720, 128)          0         
                                                                 
 lstm_4 (LSTM)               (None, 720, 128)          131584    
                                                                 
 leaky_re_lu_3 (LeakyReLU)   (None, 720, 128)          0         
                                                                 
 dropout_1 (Dropout)         (None, 720, 128)          0         
                                                                 
 lstm_5 (LSTM)               (None, 64)                49408     
                                                                 
 dropout_2 (Dropout)         (None, 64)               

- This callback will stop the training when there is no improvement in the  val_loss for three consecutive epochs.

In [ ]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = 2, mode = 'min')

In [52]:
model.compile(loss = tf.losses.MeanSquaredError(),
             optimizer = tf.optimizers.Adam(),
             metrics  = [tf.metrics.MeanAbsoluteError()])

In [ ]:
history = model.fit(train_generator, epochs = 50,
                              validation_data = test_generator,
                              shuffle = False,
                             callbacks = [early_stopping])

Epoch 1/50
447/447 [==============================] - 943s 2s/step - loss: 17193.5195 - mean_absolute_error: 77.7525 - val_loss: 12270.7188 - val_mean_absolute_error: 63.9865
Epoch 2/50
447/447 [==============================] - 952s 2s/step - loss: 14384.3818 - mean_absolute_error: 59.1097 - val_loss: 10296.7676 - val_mean_absolute_error: 47.3039
Epoch 3/50
357/447 [======================>.......] - ETA: 2:56 - loss: 12958.1748 - mean_absolute_error: 52.6510

In [ ]:
evaluate = model.evaluate_generator()